apiVersion: v1
kind: Service
metadata:
        name: jenkins
spec:
        type: LoadBalancer
        selector:
                app: jenkins 
        ports:
                - protocol: TCP 
                  port: 8080
                  targetPort: 8080
